apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-selfmanage
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MatiWall/HomeLab.Kubernetes.ClusterConfig.git
        revision: master
        directories:
          - path: apps
        values:
          namespace: argocd
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: https://github.com/MatiWall/HomeLab.Kubernetes.ClusterConfig.git
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

