apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications-helm-apps-set
  namespace: argocd
spec:
  generators:
  - git:
      revision: main
      repoURL: https://github.com/MatiWall/application-values.git
      directories:
        - path: apps
        #- path: drunkenbets-frontend
      values:
        namespace: argocd
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      destination:
        namespace: '{{ values.namespace }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: https://github.com/MatiWall/application-values.git
        helm:
          valueFiles:
            - values.yaml
        path: '{{ path }}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
