---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-selfmanage
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/MatiWall/HomeLab.ArgoCD.Applications.git
    path: apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
