---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-selfmanage-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MatiWall/HomeLab.ArgoCD.Applications.git
    path: cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true