apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: certificate-installer
  namespace: cert-manager
  labels:
    app: certificate-installer
spec:
  selector:
    matchLabels:
      app: certificate-installer
  template: 
    metadata:
      labels:
        app: certificate-installer
    spec:
      containers:
        - name: idle
          image: alpine:3.23.2
          command: ["/bin/sh", "-c", "--"]
          args: 
            - | 
              cp /tmp/secrets/local-root-ca.crt /usr/local/share/ca-certificates/local-root-ca.crt && \
              echo "Certificate installed" && \
              echo $NODE_NAME && \
              update-ca-certificates && \
              sleep infinity
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: certs
              mountPath: /tmp/secrets/local-root-ca.crt
              subPath: local-root-ca.crt
            - name: host-certs
              mountPath: /usr/local/share/ca-certificates
              
      volumes:
        - name: certs
          secret:
            secretName: local-root-ca-secret
            items:
              - key: ca.crt
                path: local-root-ca.crt
        - name: host-certs
          hostPath: 
            path: /usr/local/share/ca-certificates
            type: Directory
