apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: certificate-installer
  namespace: cert-manager
  labels:
    app: certificate-installer
spec:
  selector:
    matchLabels:
      app: certificate-installer
  template: 
    metadata:
      labels:
        app: certificate-installer
    spec:
      containers:
        - name: idle
          image: busybox
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]